APP       := Local
TARGET    := Tarsproxy
MFLAGS    :=
DFLAGS    :=
CONFIG    := client
STRIP_FLAG:= N
J2GO_FLAG:= 

libpath=${subst :, ,$(GOPATH)}
$(foreach path,$(libpath),$(eval -include C:/Users/Admin/go/src/github.com/TarsCloud/TarsGo/tars/makefile.tars))
